version: "3"
services:
  db:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
  api:
    depends_on:
      - db
    build: ./ourstore-backend
    environment:
      - FE_HOSTNAME=localhost
      - FE_PORT=80
      - PORT=5000
    # ports:
    #   - "5000:5000"
  client:
    depends_on:
      - api
    build: ./ourstore-frontend
    environment:
      - REACT_APP_BE_HOSTNAME=localhost
      - REACT_APP_BE_PORT=5000
    # ports:
    #   - "3000:3000"
  web-server:
    depends_on:
      - client
      - api
    build: ./nginx/
    ports: 
      - "80:80"
      