apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api-cluster-ip-service.yaml
- api-deployment.yaml
- client-cluster-ip-service.yaml
- client-deployment.yaml
- db-cluster-ip-service.yaml
- db-deployment.yaml
- db-pvc.yaml